### ISSUE TITLE
Rotated Transformer-memory

### ISSUE THREAD

**Issue by liminyu-web** [dwromero/g_selfatt#1]
hello~
i want to ask if i can build rotated-equivariant swin transformer anchitectural in your g_selfatt library?
thank  you!!

**Comment by jbcdnr** [comment]
Yes of course :) Feel free to fork the repo and/or submit a PR!

**Comment by liminyu-web** [comment]
hello~~
hi~i want to ask how much memory is required to run the model if the size of the input picture is 1024×1024？ i run the demo 0_local_p4_selfattention.ipynb，i put in a picture of myself，and the shape of the input_tensor is torch.Size([1, 96, 256, 256])，i can get the result of LiftLocalSelfAttention， but when i run “out_2 = sa_2(out_1)”，an error will be reported：

RuntimeError: [enforce fail at CPUAllocator.cpp:68] . DefaultCPUAllocator: can't allocate memory

Is this model unable to load large images and Is it possible to reduce patch_size

thanl you！！！！！！
