### ISSUE TITLE
Experiments environments

### ISSUE THREAD

**Issue by kbjpc123** [dwromero/g_selfatt#3]
Hi

I'd like to reproduce the results from the experiments section.
with NVIDIA TITAN Xp , training takes twice as long as table 1.

Could you please tell me which GPU you used?

**Comment by dwromero** [comment]
Hi,

yes, of course. We used TITAN RTX's for our experiments. These GPUs have more memory than then TITAN Xp's. Maybe this is the reason for the change in processing times. 

Please let me know if theres's anything else I can help with :)

Best,
David
